#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v12
# autospec commit: fbcebd0
#
Name     : bcachefs-tools
Version  : 1.7.0
Release  : 1
URL      : https://github.com/koverstreet/bcachefs-tools/archive/refs/tags/v1.7.0.tar.gz
Source0  : https://github.com/koverstreet/bcachefs-tools/archive/refs/tags/v1.7.0.tar.gz
Source1  : http://localhost/vendor/bcachefs-tools/snapshot/bcachefs-tools-2024-06-08-05-00-57.tar.xz
Summary  : Userspace tools for bcachefs
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 LGPL-2.1
Requires: bcachefs-tools-bin = %{version}-%{release}
Requires: bcachefs-tools-config = %{version}-%{release}
Requires: bcachefs-tools-data = %{version}-%{release}
Requires: bcachefs-tools-libexec = %{version}-%{release}
Requires: bcachefs-tools-man = %{version}-%{release}
Requires: bcachefs-tools-services = %{version}-%{release}
BuildRequires : libaio-dev
BuildRequires : llvm-dev
BuildRequires : pkgconfig(blkid)
BuildRequires : pkgconfig(libkeyutils)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libsodium)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(liburcu)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(udev)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The bcachefs tool, which has a number of subcommands for formatting and managing bcachefs filesystems. Run bcachefs --help for full list of commands.

%package bin
Summary: bin components for the bcachefs-tools package.
Group: Binaries
Requires: bcachefs-tools-data = %{version}-%{release}
Requires: bcachefs-tools-libexec = %{version}-%{release}
Requires: bcachefs-tools-config = %{version}-%{release}
Requires: bcachefs-tools-services = %{version}-%{release}

%description bin
bin components for the bcachefs-tools package.


%package config
Summary: config components for the bcachefs-tools package.
Group: Default

%description config
config components for the bcachefs-tools package.


%package data
Summary: data components for the bcachefs-tools package.
Group: Data

%description data
data components for the bcachefs-tools package.


%package libexec
Summary: libexec components for the bcachefs-tools package.
Group: Default
Requires: bcachefs-tools-config = %{version}-%{release}

%description libexec
libexec components for the bcachefs-tools package.


%package man
Summary: man components for the bcachefs-tools package.
Group: Default

%description man
man components for the bcachefs-tools package.


%package services
Summary: services components for the bcachefs-tools package.
Group: Systemd services
Requires: systemd

%description services
services components for the bcachefs-tools package.


%prep
%setup -q -n bcachefs-tools-1.7.0
cd %{_builddir}
tar xf %{_sourcedir}/bcachefs-tools-2024-06-08-05-00-57.tar.xz
cd %{_builddir}/bcachefs-tools-1.7.0
mkdir -p ./vendor
cp -r %{_builddir}/bcachefs-tools-2024-06-08-05-00-57/* %{_builddir}/bcachefs-tools-1.7.0/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1718713885
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}  PREFIX=/usr


%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make tests

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1718713885
rm -rf %{buildroot}
export GOAMD64=v2
GOAMD64=v2
%make_install PREFIX=/usr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bcachefs
/usr/bin/fsck.bcachefs
/usr/bin/fsck.fuse.bcachefs
/usr/bin/mkfs.bcachefs
/usr/bin/mkfs.fuse.bcachefs
/usr/bin/mount.bcachefs
/usr/bin/mount.fuse.bcachefs

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/64-bcachefs.rules

%files data
%defattr(-,root,root,-)
/usr/share/initramfs-tools/hooks/bcachefs
/usr/share/initramfs-tools/scripts/local-premount/bcachefs

%files libexec
%defattr(-,root,root,-)
/usr/libexec/bcachefsck_all
/usr/libexec/bcachefsck_fail

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/bcachefs.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/bcachefsck@.service
/usr/lib/systemd/system/bcachefsck_all.service
/usr/lib/systemd/system/bcachefsck_all.timer
/usr/lib/systemd/system/bcachefsck_all_fail.service
/usr/lib/systemd/system/bcachefsck_fail@.service
/usr/lib/systemd/system/system-bcachefsck.slice
